/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfirmRouteImport } from './routes/confirm'
import { Route as ExamRouteImport } from './routes/exam'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResultRouteImport } from './routes/result'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as CoordinatorIndexRouteImport } from './routes/coordinator/index'
import { Route as CoordinatorDashboardRouteImport } from './routes/coordinator/dashboard'
import { Route as CoordinatorQuestionsRouteImport } from './routes/coordinator/questions'
import { Route as CoordinatorSettingsRouteImport } from './routes/coordinator/settings'
import { Route as CoordinatorParticipantsIdRouteImport } from './routes/coordinator/participants.$id'
import { Route as CoordinatorQuestionsIndexRouteImport } from './routes/coordinator/questions.index'
import { Route as CoordinatorQuestionsIdRouteImport } from './routes/coordinator/questions.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmRoute = ConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRoute = ExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordinatorIndexRoute = CoordinatorIndexRouteImport.update({
  id: '/coordinator/',
  path: '/coordinator/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordinatorDashboardRoute = CoordinatorDashboardRouteImport.update({
  id: '/coordinator/dashboard',
  path: '/coordinator/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordinatorQuestionsRoute = CoordinatorQuestionsRouteImport.update({
  id: '/coordinator/questions',
  path: '/coordinator/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordinatorSettingsRoute = CoordinatorSettingsRouteImport.update({
  id: '/coordinator/settings',
  path: '/coordinator/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordinatorParticipantsIdRoute =
  CoordinatorParticipantsIdRouteImport.update({
    id: '/coordinator/participants/$id',
    path: '/coordinator/participants/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoordinatorQuestionsIndexRoute =
  CoordinatorQuestionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CoordinatorQuestionsRoute,
  } as any)
const CoordinatorQuestionsIdRoute = CoordinatorQuestionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CoordinatorQuestionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirm': typeof ConfirmRoute
  '/exam': typeof ExamRoute
  '/register': typeof RegisterRoute
  '/result': typeof ResultRoute
  '/rules': typeof RulesRoute
  '/coordinator/dashboard': typeof CoordinatorDashboardRoute
  '/coordinator/questions': typeof CoordinatorQuestionsRouteWithChildren
  '/coordinator/settings': typeof CoordinatorSettingsRoute
  '/coordinator/': typeof CoordinatorIndexRoute
  '/coordinator/participants/$id': typeof CoordinatorParticipantsIdRoute
  '/coordinator/questions/$id': typeof CoordinatorQuestionsIdRoute
  '/coordinator/questions/': typeof CoordinatorQuestionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirm': typeof ConfirmRoute
  '/exam': typeof ExamRoute
  '/register': typeof RegisterRoute
  '/result': typeof ResultRoute
  '/rules': typeof RulesRoute
  '/coordinator/dashboard': typeof CoordinatorDashboardRoute
  '/coordinator/settings': typeof CoordinatorSettingsRoute
  '/coordinator': typeof CoordinatorIndexRoute
  '/coordinator/participants/$id': typeof CoordinatorParticipantsIdRoute
  '/coordinator/questions/$id': typeof CoordinatorQuestionsIdRoute
  '/coordinator/questions': typeof CoordinatorQuestionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/confirm': typeof ConfirmRoute
  '/exam': typeof ExamRoute
  '/register': typeof RegisterRoute
  '/result': typeof ResultRoute
  '/rules': typeof RulesRoute
  '/coordinator/dashboard': typeof CoordinatorDashboardRoute
  '/coordinator/questions': typeof CoordinatorQuestionsRouteWithChildren
  '/coordinator/settings': typeof CoordinatorSettingsRoute
  '/coordinator/': typeof CoordinatorIndexRoute
  '/coordinator/participants/$id': typeof CoordinatorParticipantsIdRoute
  '/coordinator/questions/$id': typeof CoordinatorQuestionsIdRoute
  '/coordinator/questions/': typeof CoordinatorQuestionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirm'
    | '/exam'
    | '/register'
    | '/result'
    | '/rules'
    | '/coordinator/dashboard'
    | '/coordinator/questions'
    | '/coordinator/settings'
    | '/coordinator/'
    | '/coordinator/participants/$id'
    | '/coordinator/questions/$id'
    | '/coordinator/questions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirm'
    | '/exam'
    | '/register'
    | '/result'
    | '/rules'
    | '/coordinator/dashboard'
    | '/coordinator/settings'
    | '/coordinator'
    | '/coordinator/participants/$id'
    | '/coordinator/questions/$id'
    | '/coordinator/questions'
  id:
    | '__root__'
    | '/'
    | '/confirm'
    | '/exam'
    | '/register'
    | '/result'
    | '/rules'
    | '/coordinator/dashboard'
    | '/coordinator/questions'
    | '/coordinator/settings'
    | '/coordinator/'
    | '/coordinator/participants/$id'
    | '/coordinator/questions/$id'
    | '/coordinator/questions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfirmRoute: typeof ConfirmRoute
  ExamRoute: typeof ExamRoute
  RegisterRoute: typeof RegisterRoute
  ResultRoute: typeof ResultRoute
  RulesRoute: typeof RulesRoute
  CoordinatorDashboardRoute: typeof CoordinatorDashboardRoute
  CoordinatorQuestionsRoute: typeof CoordinatorQuestionsRouteWithChildren
  CoordinatorSettingsRoute: typeof CoordinatorSettingsRoute
  CoordinatorIndexRoute: typeof CoordinatorIndexRoute
  CoordinatorParticipantsIdRoute: typeof CoordinatorParticipantsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm': {
      id: '/confirm'
      path: '/confirm'
      fullPath: '/confirm'
      preLoaderRoute: typeof ConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam': {
      id: '/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordinator/': {
      id: '/coordinator/'
      path: '/coordinator'
      fullPath: '/coordinator/'
      preLoaderRoute: typeof CoordinatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordinator/dashboard': {
      id: '/coordinator/dashboard'
      path: '/coordinator/dashboard'
      fullPath: '/coordinator/dashboard'
      preLoaderRoute: typeof CoordinatorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordinator/questions': {
      id: '/coordinator/questions'
      path: '/coordinator/questions'
      fullPath: '/coordinator/questions'
      preLoaderRoute: typeof CoordinatorQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordinator/settings': {
      id: '/coordinator/settings'
      path: '/coordinator/settings'
      fullPath: '/coordinator/settings'
      preLoaderRoute: typeof CoordinatorSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordinator/participants/$id': {
      id: '/coordinator/participants/$id'
      path: '/coordinator/participants/$id'
      fullPath: '/coordinator/participants/$id'
      preLoaderRoute: typeof CoordinatorParticipantsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordinator/questions/': {
      id: '/coordinator/questions/'
      path: '/'
      fullPath: '/coordinator/questions/'
      preLoaderRoute: typeof CoordinatorQuestionsIndexRouteImport
      parentRoute: typeof CoordinatorQuestionsRoute
    }
    '/coordinator/questions/$id': {
      id: '/coordinator/questions/$id'
      path: '/$id'
      fullPath: '/coordinator/questions/$id'
      preLoaderRoute: typeof CoordinatorQuestionsIdRouteImport
      parentRoute: typeof CoordinatorQuestionsRoute
    }
  }
}

interface CoordinatorQuestionsRouteChildren {
  CoordinatorQuestionsIdRoute: typeof CoordinatorQuestionsIdRoute
  CoordinatorQuestionsIndexRoute: typeof CoordinatorQuestionsIndexRoute
}

const CoordinatorQuestionsRouteChildren: CoordinatorQuestionsRouteChildren = {
  CoordinatorQuestionsIdRoute: CoordinatorQuestionsIdRoute,
  CoordinatorQuestionsIndexRoute: CoordinatorQuestionsIndexRoute,
}

const CoordinatorQuestionsRouteWithChildren =
  CoordinatorQuestionsRoute._addFileChildren(CoordinatorQuestionsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfirmRoute: ConfirmRoute,
  ExamRoute: ExamRoute,
  RegisterRoute: RegisterRoute,
  ResultRoute: ResultRoute,
  RulesRoute: RulesRoute,
  CoordinatorDashboardRoute: CoordinatorDashboardRoute,
  CoordinatorQuestionsRoute: CoordinatorQuestionsRouteWithChildren,
  CoordinatorSettingsRoute: CoordinatorSettingsRoute,
  CoordinatorIndexRoute: CoordinatorIndexRoute,
  CoordinatorParticipantsIdRoute: CoordinatorParticipantsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
